---
- hosts: all
  tasks:
  - name: Copy a single file where the source is on the remote host
    win_copy:
       src: \\10.176.133.3\test\test.txt
       dest: D:\
       remote_src: yes
    become: True
    become_method: runas 
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    vars:
       ansible_become_user: a_c_avenkat
       ansible_become_pass: W3c0le1@#$%123
    

 
