---
- hosts: all
  tasks:
  - name: Copy a single file where the source is on the remote host
    win_copy:
       src: \\ivanti\VDI Patches\proxyex.txt
       dest: C:\temp\
       remote_src: no

 
