---
- hosts: localhost
  tasks:
  - uri:
      url: 'https://dfs-fs-sandbox.freshservice.com/api/v2/assets'
      method: POST
      url_username: CNbsMFQn9LDynLiPd0oL
      url_password: Welcome@#$
      body:
         {"name":"xsininfrpmgt100001","asset_type_id":13000759193,"impact":"low","usage_type":"permanent","description":"Test Create","location_id":null,"agent_id":null,"department_id":null,"group_id":null,"type_fields":{"os_version_13000759193":"windows server 2016"}}
      force_basic_auth: yes
      status_code: -1
      body_format: json
      headers:
         Content-Type: 'application/json'
    register: result
  - name:
    debug: var=result.stdout_lines
